FROM osgeo/gdal:ubuntu-small-latest

ARG POSTGRES_USER=postgres
ARG POSTGRES_PASSWORD=postgres
ARG POSTGRES_DB=geo

ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}

COPY ./docker-entrypoint.sh /
RUN ["chmod", "+x", "/docker-entrypoint.sh"]

# Set up project directory
COPY ./app/db/ddl.sql /docker-entrypoint-initdb.d/ddl.sql
COPY ./insert_data.py /docker-entrypoint-initdb.d/insert_data.py

# copy data
COPY ./data/nsw_polygon.json /data/nsw_polygon.json
COPY ./data/nsw_poi.json /data/nsw_poi.json
COPY ./data/nsw_neighborhood.json /data/nsw_neighborhood.json

RUN apt-get update \
  && apt install software-properties-common -y \
  && apt-get install -y build-essential wget curl unzip --no-install-recommends

# install Postgres and PostGIS
RUN apt update \
  && apt install -y postgresql-12 postgis \
  && apt install -y vim

# python and gis libs
RUN apt-get install -y pip
RUN pip install geopandas GeoAlchemy2
RUN apt-get install --reinstall libpq-dev
RUN pip install psycopg2

RUN service postgresql start
COPY ./app/db/postgresql.conf /etc/postgresql/12/main/postgresql.conf
COPY ./app/db/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
RUN service postgresql restart

# start postgres and create user
USER postgres

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 5432