name: Test and Codecov
on:
  push:
    branches:
      - main
      - dev
      - test
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: geo
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        # architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install libraries
      run: pip install -r requirements.txt
    - name: Create tables
      run: PGPASSWORD=${{ env.DB_PASSWORD }} psql -U ${{ env.DB_USERNAME }} -h ${{ env.DB_HOST }} -d ${{ env.DB_NAME }} -f app/sql/ddl.sql
    - name: Insert data
      run: |
        sudo add-apt-repository ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install gdal-bin
        ogrinfo --version
        ogr2ogr -f "PostgreSQL" PG:"host=${{ env.DB_HOST }} port=${{ env.DB_PORT }} dbname=${{ env.DB_NAME }} user=${{ env.DB_USERNAME }} password=${{ env.DB_PASSWORD }}" "data/out/nsw_polygon.json" -nln nsw_polygon -nlt POLYGON
        ogr2ogr -f "PostgreSQL" PG:"host=${{ env.DB_HOST }} port=${{ env.DB_PORT }} dbname=${{ env.DB_NAME }} user=${{ env.DB_USERNAME }} password=${{ env.DB_PASSWORD }}" "data/out/nsw_poi.json" -nln nsw_poi -nlt POLYGON
        ogr2ogr -f "PostgreSQL" PG:"host=${{ env.DB_HOST }} port=${{ env.DB_PORT }} dbname=${{ env.DB_NAME }} user=${{ env.DB_USERNAME }} password=${{ env.DB_PASSWORD }}" "data/out/nsw_neighborhood_sample.json" -nln nsw_neighborhood -nlt POLYGON
    - name: Test
      run: pytest --verbose --color=yes --cov=app --cov-report=xml
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
        # verbose: true
        
